variables:
  PROJECT_VERSION: 1.2-SNAPSHOT
  SLS_IMAGE: registry.gitlab.ost.ch:45023/stefan.kapferer/serverless-framework-docker-image/sls:v1.0

stages:
  - build
  - deploy

maven-build:
  stage: build
  image: openjdk:17-alpine
  script:
    - echo "Building application..."
    - ./mvnw clean package
    - echo "Application successfully built."
  artifacts:
    paths:
      - target/tla-sample-serverless-${PROJECT_VERSION}-aws.jar

deploy:
  stage: deploy
  image: $SLS_IMAGE
  environment: dev
  variables:
    SERVERLESS_ACCESS_KEY: $SERVERLESS_ACCESS_KEY
  only:
    refs:
      - main
  script:
    - echo "Deploying application..."
    - sls deploy --debug
    - sls invoke --function seed_database --data 'unused'
    - echo "Application successfully deployed."

undeploy:
  stage: deploy
  image: $SLS_IMAGE
  environment: dev
  variables:
    SERVERLESS_ACCESS_KEY: $SERVERLESS_ACCESS_KEY
  when: manual
  only:
    refs:
      - main
  script:
    - echo "Undeploying application..."
    - sls remove
    - echo "Application successfully undeployed."
