name: Build and deploy main branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tla-manager-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install Graphviz
        run: sudo apt-get -y install graphviz
      - name: Build with Maven
        run: |
          cd tla-manager
          mvn -B package --file pom.xml
      - uses: actions/cache@v4
        id: cache-target-manager
        with:
          path: tla-manager/target
          key: tla-sample-app-serverless-manager-${{ github.run_id }}

  tla-resolver-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'
      - name: Build with Make
        run: |
          cd tla-resolver
          make build
      - uses: actions/cache@v4
        id: cache-target-resolver
        with:
          path: tla-resolver/dist
          key: tla-sample-app-serverless-resolver-${{ github.run_id }}

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [tla-manager-build, tla-resolver-build]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/cache@v4
        id: cache-target-manager
        with:
          path: tla-manager/target
          key: tla-sample-app-serverless-manager-${{ github.run_id }}
      - uses: actions/cache@v4
        id: cache-target-resolver
        with:
          path: tla-resolver/dist
          key: tla-sample-app-serverless-resolver-${{ github.run_id }}
      - run: npm install -g serverless
      - name: Deploy tla-manager
        run: |
          cd tla-manager
          serverless deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      - name: Seed database
        run: |
          cd tla-manager
          serverless invoke --function seed_database --data 'unused'
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      - name: Deploy tla-resolver
        run: |
          cd tla-resolver
          serverless deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
